services:
  - type: web
    name: telegram-redpacket-control
    runtime: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: USER_API_ID
        sync: false
      - key: USER_API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: YOUR_USER_ID
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.12
